---
title: "lab5part2"
author: "Grace Bianchi"
date: "2023-02-09"
output: html_document:
  code_folding: hide
---

```{r setup, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)

library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

```

### Read in excel file and wrangle the data

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  janitor::clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% # identifies columns where is character is true
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% # drops astreisks
  filter(confidentiality == 'public')
```

```{r}
fish_plot <- ggplot(data = fish_noaa, 
                    aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() 

ggplotly(fish_plot) # interactive plot

### highlight series based on condition
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) + 
  geom_line() +
  gghighlight(nmfs_name == "rockfishes") + ### highlights just this group
  theme_minimal()

# highlight group given specific conditions
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) + 
  geom_line(aes(color = nmfs_name)) +
  gghighlight(max(pounds) > 1e8) + ### highlights groups that match this criterion
  theme_minimal()

```

```{r}
monroe_data <- read_csv("https://raw.githubusercontent.com/oharac/esm244_w2023_lab5/master/data/MWTP_Elec_Daily.csv") %>%  janitor::clean_names()

monroe_ts <- monroe_data %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(record_month = lubridate::month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month)) # reordering months using month number(record_month)
  
ggplot(data = monroe_ts, aes(x = month_name, y = total_kwh)) +
  geom_jitter(aes(color = month_name),
              show.legend = FALSE,
              alpha = 0.5,
              size = 0.3,
              width = 0.2) + # spacing in x direction
  theme_classic()
```

